cluster.name: docker-cluster
network.host: 0.0.0.0

ingest.geoip.downloader.enabled: false

xpack.license.self_generated.type: trial
xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: true
