version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kolay
      - POSTGRES_DB=loan_service_db
    image: postgres:12.13-alpine3.17
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 10s
      retries: 3
#    volumes:
#      - postgres:/var/lib/postgresql/data
  loan-service:
    build:
      dockerfile: Dockerfile
    image: 'loan-service'
    container_name: loan-service
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: loan_service_db
      POSTGRES_PASSWORD: kolay
    depends_on:
      - db