version: '3.5'

services:
  postgres:
    image: postgres:12.13-alpine3.17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loan_service_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - "/db-data/var/lib/postgresql/data"

  loan-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar loan-service.jar
    image: 'loan-service'
    container_name: loan-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/loan_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loan_service_db
    depends_on:
      - postgres

  grafana:
    build: './scripts/config/grafana'
    ports:
      - "3030:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/config/prometheus.yaml:/etc/prometheus/prometheus.yaml